stages:
  - build
  - deploy

compile-dan-test:
  image: maven:3.9.4-eclipse-temurin-17-alpine
  stage: build
  services:
    - postgres:15
  variables:
    POSTGRES_DB: contact_management_db
    POSTGRES_USER: dani
    POSTGRES_PASSWORD: dani
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/contact_management_db
  script: mvn clean package
  artifacts:
    paths:
      - target/*.jar