services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=contact_management_db'
      - 'POSTGRES_PASSWORD=dani'
      - 'POSTGRES_USER=dani'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - '$PWD/restful-api-contact-management-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    expose:
      - '5432'