services:
  db-contact-management:
    image: 'postgres:16'
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - 'POSTGRES_DB=contact_management_db'
      - 'POSTGRES_USER=dani'
      - 'POSTGRES_PASSWORD=dani'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - '$PWD/db-contact-management:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    expose:
      - '5432'

  vault:
    image: hashicorp/vault
    restart: always
    command: ['vault', 'server', '-dev', '-dev-listen-address=0.0.0.0:8288']
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root-token-for-dev-purpose-only'
    ports:
      - '8288:8288'
    expose:
      - '8288'