apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend-contact-management
  labels:
    app: contact-management
    tier: backend
    stage: dev
    ver: v2024070905
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-management
      tier: backend
      stage: dev
      ver: v2024070905
  template:
    metadata:
      labels:
        app: contact-management
        tier: backend
        stage: dev
        ver: v2024070905
    spec:
      serviceAccountName: sa-contact-management
      containers:
      - name: container-backend-contact-management
        image: 2819930922/contact-management-api:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: 1331Mi     # Maximum memory usage is 1.3 GiB
            cpu: 600m          # Maximum CPU usage is 60% of 1 CPU core (600 millicores)
          limits:
            memory: 2Gi        # Guaranteed 2 GiB of memory
            cpu: 1000m         # Guaranteed 1 CPU core
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: konfigurasi-app-contact-management
              key: database_jdbc_url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-contact-management
              key: database_username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-contact-management
              key: database_password
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-dari-vault
          mountPath: "/mnt/secrets-store"
          readOnly: true
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: secret-dari-vault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-database"

---
apiVersion: v1
kind: Service
metadata:
  name: service-backend-contact-management
  labels:
    app: contact-management
    tier: backend
    stage: dev
    ver: v2024070905
spec:
  ports:
  - port: 8080
  selector:
    app: contact-management
    tier: backend
    stage: dev
    ver: v2024070905

---
# The following is responsible for the autoscaling.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-backend-contact-management
spec:
  scaleTargetRef:
    kind: Deployment
    name: deployment-backend-contact-management
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60